### ISSUE TITLE
Missing questions in Microsoft article

### ISSUE THREAD

**Issue by rishabh115** [twowaits/SDE-Interview-Questions#100]
Aforementioned article lacks the technical interview round questions. Anyone taking this issue must follow the contributing guidelines.

**Comment by Ipsit1234** [comment]
@rishabh115 I want to take this up. Can I do that?

**Comment by Anita-ihuman** [comment]
Can I tackle this issue?

**Comment by rishabh115** [comment]
Sure, thanks!

**Comment by Anita-ihuman** [comment]
Alright but I might be needing a detailed explanation of how to go about it

**Comment by rishabh115** [comment]
> Alright but I might be needing a detailed explanation of how to go about it

Go through the contributing guidelines, it has everything you need to know.

**Comment by root-ansh** [comment]
can i add some questions to the Microsoft section? My friend went till 3 or 4 rounds , so I know some questions asked there

**Comment by Manali21Gupta** [comment]
Can i do this?

**Comment by prashant314** [comment]
Hello @rishabh115 can I work on this?

**Comment by rishabh115** [comment]
Sure. Just make sure you have read the contributing guidelines and you are good to go. Happy coding ✌️

**Comment by prashant314** [comment]
Hello @rishabh115  I have added questions for this Mircosoft article. Please review my PR. Thanks.

**Comment by sakshi006** [comment]
Hey, can i contribute to this?

**Comment by sakshi006** [comment]
Hey @rishabh115  I have made a PR. Kindly review it.
