### ISSUE TITLE
Incomplete Adobe article, need to add more questions!

### ISSUE THREAD

**Issue by rishabh115** [twowaits/SDE-Interview-Questions#119]
Currently, this article is in initial phase. Anyone taking this issue must ensure adding some questions in all the section as specified in contributing guidelines.  Happy coding🤟!

**Comment by JoaoVictorNascimento** [comment]
I will make this issue

**Comment by JoaoVictorNascimento** [comment]
@rishabh115 I need authorization for the pull request

**Comment by ayushi-1408** [comment]
Hey! I would love to work on this issue

**Comment by rishabh115** [comment]
> I will make this issue

Assigned you the issue. Create a completed article while following contributing guidelines.
