### ISSUE TITLE
Missing questions in Amazon article

### ISSUE THREAD

**Issue by rishabh115** [twowaits/SDE-Interview-Questions#120]
Coding round and technical interview round questions are almost non-existent in this article. Anyone taking this issue should add some questions to all the aforementioned or blank sections while keeping contributing guidelines in mind. Geeksforgeeks has lot of articles regarding Amazon. It would be great if someone properly enhance the article rather than symbolic contributon of 1 question or fixing typos.

**Comment by JoaoVictorNascimento** [comment]
I would like to do this issue

**Comment by deepti23-web** [comment]
I would like to work on this. Can you please assign this to me?

**Comment by ayushi-1408** [comment]
Hey! I would love to work on this issue.

**Comment by rishabh115** [comment]
> Hey! I would love to work on this issue.

Assigned you the issue. Do create a good article. Happy Coding✌️
