### ISSUE TITLE
Need better approach for aligning article hyperlinks in top-level Readme

### ISSUE THREAD

**Issue by rishabh115** [twowaits/SDE-Interview-Questions#132]
As of now, companies articles are aligned in the form of bulleted unordered list. But the problem with this approach is that as soon as we have properly completed articles of more companies, it will turn into a big mess. 
Have seen alphabetical grid approach in multiple awesome prefixed repos. If the same can be implemented here, then it will look well ordered and presented.

**Comment by Hinal-Srivastava** [comment]
I can do it👍

**Comment by sumitkumarju** [comment]
hey, can you elaborate with an example??

**Comment by rishabh115** [comment]
> hey, can you elaborate with an example??

()[https://repository-images.githubusercontent.com/40781164/f3534200-e366-11e9-8a3f-61cf3118db85]
Something like this where in the place of icons, there will be alphabets and once you click on that alphabet, focus will be shifted to companies section starting with that letter.

**Comment by dsibilio** [comment]
@rishabh115 wouldn't something like this make information equally accessible without having to jump inbetween sections? _(For the sake of simplicity i excluded companies links, but you can imagine each company name holds a reference to the correct section of the repo)_

| | Companies|
| ------ | ------ |
| **E** | Expedia |
| **F** | Facebook | 
| **G** | Google | 
| **...** | Example, Of, Many, Companies, Separated, By, Commas, The, Table, Is, Responsive, The, Text, Automatically, Line, Breaks, This, Is, Not, Bad, After, All, :-) |
