### ISSUE TITLE
New Google Coding Round Question

### ISSUE THREAD

**Issue by BittuRoxs** [twowaits/SDE-Interview-Questions#142]
Counting Subarrays
You are given an array that contians N positive integers a1,a2...aN, where all ai are pairwise distiinct. For each ai, you are required to determine the number of subarrys such that the minimum value of the subarray is ai.
A subarray is a contigious set of elements of an array 

I would like to add this question
Please assign this issue to me.
Label : Hacktoberfest2020

**Comment by rishabh115** [comment]
> Counting Subarrays
> You are given an array that contians N positive integers a1,a2...aN, where all ai are pairwise distiinct. For each ai, you are required to determine the number of subarrys such that the minimum value of the subarray is ai.
> A subarray is a contigious set of elements of an array
> 
> I would like to add this question
> Please assign this issue to me.
> Label : Hacktoberfest2020

Please read the contributing guidelines and hacktoberfest rules.
