### ISSUE TITLE
Missing questions in Google article!

### ISSUE THREAD

**Issue by rishabh115** [twowaits/SDE-Interview-Questions#151]
Aforementioned article lacks the technical interview round questions. It needs to be comprehensive covering questions across all rounds. Anyone taking this issue must follow the contributing guidelines.

**Comment by aakashg34** [comment]
I would like to work on this, please assign me this part

**Comment by khushibalyan220101** [comment]
I can do this kindly assign it to me sir.

**Comment by priyanka001tech** [comment]
I would like to add Google  technical interview round questions. Please assign me to this.

**Comment by sakshi006** [comment]
Hey @rishabh115  Can i work on this?

**Comment by rishabh115** [comment]
@khushibalyan220101 @aakashg34 @priyanka001tech @sakshi006 I have assigned the issues to you. Please try to add as much questions as possible across section following contributing guidelines. Happy Coding ✌️

**Comment by SabhyaGrover** [comment]
I would like to work on this.
