### ISSUE TITLE
Yelp interview questions

### ISSUE THREAD

**Issue by gnp31** [twowaits/SDE-Interview-Questions#153]
I would like to add Yelp interview questions.
Please assign me to this.

**Comment by rishabh115** [comment]
> I would like to add Yelp interview questions.
> Please assign me to this.

Make sure you follow the contributing guidelines and add atleast 10-15 questions across multiple sections. Happy Coding✌️

**Comment by gnp31** [comment]
I have made a PR. Please check

**Comment by kshsh00** [comment]
Can I also be assigned??
