### ISSUE TITLE
kindly add "hacktober-accepted" on all merged PRs

### ISSUE THREAD

**Issue by anjali1102** [twowaits/SDE-Interview-Questions#169]
pls add "hacktober-accepted" label to my merged PR #103 and all others else the review will not be taken ahead

**Comment by rishabh115** [comment]
> pls add "hacktober-accepted" label to my merged PR #103 and all others else the review will not be taken ahead

Hi @anjali1102, **hacktoberfest-accepted** label is for repos not having hacktoberfest tag. There is no need to worry. FAQ of hacktoberfest has made it crystal clear.

> > What do I do if I want to contribute to a project but it doesn’t have the hacktoberfest topic?
> 
> ﹢
> You can still contribute to any public GitHub repository and have it count towards your progress provided that your pull request is labeled with hacktoberfest-accepted.

>
