### ISSUE TITLE
Project not participating in Hacktoberfest 2021

### ISSUE THREAD

**Issue by uvasistha** [twowaits/SDE-Interview-Questions#237]
Question : Is this project not participating in Hacktoberfest 2021 ?
Reason for raising Issue : Contribution Profile for Hacktoberfest 2021 says "Project not participating" after 2nd contribution to this repository.

**Comment by rishabh115** [comment]
Hi @uvasistha, There were spam pull request being on the repo since the starting of Hacktoberfest and also many people reported regarding it. So we decided remove it from Hacktoberfest. Thanks for your contribution and sorry for the takedown.
