### ISSUE TITLE
need to add another question that I was asked recently at uber

### ISSUE THREAD

**Issue by Ambuj-K** [twowaits/SDE-Interview-Questions#93]
The question I was asked is, 

A segment of arbitrary size, how do we tell that it is captured or not.
E - Empty, 1 - Color 1, 2 - Color 2

EE1111EE
EE1221EE
EE1221EE
EE1111EE Captured

EE1111EE
EE1221EE
EE1221EE
E1221EEE
E1111EEE Captured

EE1111EE
EE1221EE
EE2221EE
EE111EEE Not Captured

I would like to add it, and if someone can suggest a solution I'd be grateful

**Comment by rishabh115** [comment]
Hi @Ambuj-K, Thanks for your question. The criteria for segment being captured  or not is little unclear. It would be very helpful, if you can add the revised question in a new pull request. Meanwhile, here is the **[contributing guideline](https://github.com/rishabh115/SDE-Interview-Questions/blob/master/CONTRIBUTING.md)**. Cheers🤟!

**Comment by ravireddy07** [comment]
After looking into samples above, @rishabh115 

Color 1 & Color 2 is acting like a positive and negative to balance the pattern. Which ever pattern is balanced is Captured, else Not Captured. Is this true...?

@Ambuj-K  Please conform this, I'll provide the algorithm & code for this.

**Comment by abitaaugustine** [comment]
Hey if you are to open a new issue for hacktoberfest I can add the questions from ThoughtWorks, TCS, WIPRO interviews?

**Comment by abitaaugustine** [comment]
> Hey if you are to open a new issue for hacktoberfest I can add the questions from ThoughtWorks, TCS, WIPRO interviews?

Or should I just fork edit and then create a pull request

**Comment by ravireddy07** [comment]
@rishabh115  Hi, do we need to create only code or only Description of the problem statement or both...?

**Comment by rishabh115** [comment]
Guys, Have a look at the contributing guidelines. It has everything you need to know.

**Comment by abitaaugustine** [comment]
I have added the questions I was asked for ThoughtWorks interview @rishabh115
